/**
 * `styles/tokens.css` is a build output, and this holds it to its source.
 *
 * The file stays a linked stylesheet because every declaration in it is PRE-PAINT — the kit's own
 * theme is adopted from JavaScript at boot — so the tests that matter are the ones about what the
 * generated bytes actually say, not merely that a generator ran.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expandRule, readSource, run, tokensCSS } from "../scripts/build-tokens";

const ROOT = join(import.meta.dir, "..");
const css = readFileSync(join(ROOT, "styles/tokens.css"), "utf8");

describe("the committed stylesheet is what its source means", () => {
  test("tokens.css matches tokens.json, which is the gate CI runs", async () => {
    expect(await run(ROOT, false)).toBe(true);
  });

  test("it says it is generated, and names the file to edit instead", () => {
    expect(css).toContain("GENERATED FILE — do not edit.");
    expect(css).toContain("styles/tokens.json");
    expect(css).toContain("tokens:sync");
  });
});

describe("what the generated sheet must contain", () => {
  test("three JetBrains Mono faces, each emitted exactly once", () => {
    /* The reason the platform grew an array under a declaration at-rule (spec.md §9.2): an object's
       keys are unique, so one `@font-face` key could state one weight. Before that an array emitted
       NOTHING, so the assertion that matters is the count. */
    expect(css.match(/@font-face \{/g)?.length).toBe(3);
    for (const weight of ["400", "500", "700"]) {
      expect(css, weight).toContain(`url("../fonts/jetbrains-mono-${weight}.woff2")`);
      expect(css.match(new RegExp(`jetbrains-mono-${weight}\\.woff2`, "g"))?.length).toBe(1);
    }
    // Relative to `styles/`, which is where this file is and why it may not move.
    expect(css).not.toContain('url("fonts/');
  });

  test("the panel widths are on :root, where the resize logic writes them", () => {
    /* `panel-resize.ts` writes these as inline styles on `document.documentElement`. A declaration
       on any closer ancestor of #app would shadow that inline override and freeze the sidebars, so
       the ONLY correct home is the root rule. */
    const root = css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {")));
    expect(root).toContain("--panel-w-left: 240px;");
    expect(root).toContain("--panel-w-right: 280px;");
  });

  test("the reset reaches the root element as well as everything under it", () => {
    /* `*` matched `html`; `:root *` does not. The two declarations are therefore written twice on
       purpose — once on the root, once on its descendants — and dropping the root half would leave
       `html` with a box-sizing the rest of the page does not have. */
    expect(css).toContain(":root *,\n:root *::before,\n:root *::after {");
    const root = css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {")));
    expect(root).toContain("box-sizing: border-box;");
    expect(root).toContain("margin: 0;");
  });

  test("the shell fills the viewport and the light boot has its own backdrop", () => {
    expect(css).toContain(":root body {");
    expect(css).toContain("background: var(--jx-bg, #111114);");
    expect(css).toContain(':root[data-theme="light"],\n:root[data-theme="light"] body {');
    expect(css).toContain("background: var(--jx-bg, #f7f7f9);");
  });

  test("every semantic token is an alias of a kit token, with a hex fallback", () => {
    // What `check-styles.ts` reads to hold the guidelines table; the shape is load-bearing for it.
    for (const [token, kit] of [
      ["--bg", "--jx-bg"],
      ["--fg", "--jx-fg"],
      ["--accent", "--jx-accent"],
      ["--radius", "--jx-radius-sm"],
    ]) {
      expect(css, token).toContain(`${token}: var(${kit}, `);
    }
  });

  test("no Spectrum name survives here — those live in the file with a death date", () => {
    expect(css).not.toContain("--spectrum-");
    expect(css).not.toContain("sp-theme");
    const spectrum = readFileSync(join(ROOT, "styles/spectrum.css"), "utf8");
    expect(spectrum).toContain("sp-theme {");
    expect(spectrum).toContain("--spectrum-");
  });
});

describe("expandRule", () => {
  test("puts one declaration on each line", () => {
    expect(expandRule(":root { a: 1; b: 2 }")).toBe(":root {\n  a: 1;\n  b: 2;\n}");
  });

  test("puts one selector on each line, which is the shape oxfmt would impose anyway", () => {
    /* Not cosmetic: `bun run format` rewrites every tracked `.css`, so a generator emitting any
       other shape is undone by the next format and leaves the gate red with nothing wrong. */
    expect(expandRule("a, b::before { c: 1 }")).toBe("a,\nb::before {\n  c: 1;\n}");
    // A comma inside `:is()` separates nothing, so the splitter has to be selector-aware.
    expect(expandRule(":is(a, b) c { d: 1 }")).toBe(":is(a, b) c {\n  d: 1;\n}");
  });

  test("a semicolon inside quotes or parentheses is part of a value", () => {
    /* The reason this is written rather than a `split(";")`: a font stack and a `color-mix()` both
       carry punctuation, and breaking one produces a declaration that parses as nothing. */
    expect(expandRule(`:root { --f: "a;b"; --g: 1 }`)).toBe(`:root {\n  --f: "a;b";\n  --g: 1;\n}`);
    expect(expandRule(":root { --c: color-mix(in oklab, a 6%, b); --d: 2 }")).toBe(
      ":root {\n  --c: color-mix(in oklab, a 6%, b);\n  --d: 2;\n}",
    );
  });

  test("leaves a rule with no body, and text that is no rule, alone", () => {
    expect(expandRule(":root { }")).toBe(":root {\n}");
    expect(expandRule("/* a comment */")).toBe("/* a comment */");
  });
});

describe("the source", () => {
  test("is a style block the builder reads, and the fonts are a list", async () => {
    const style = await readSource(ROOT);
    expect(Array.isArray(style["@font-face"])).toBe(true);
    expect((style["@font-face"] as unknown[]).length).toBe(3);
  });

  test("a change to the source changes the output, which is what the gate compares", () => {
    const before = tokensCSS({ color: "red" });
    const after = tokensCSS({ color: "blue" });
    expect(before).not.toBe(after);
    expect(after).toContain("color: blue;");
  });
});
