/**
 * `styles/tokens.css` is a build output, and this holds it to its source.
 *
 * The file stays a linked stylesheet because every declaration in it is PRE-PAINT — the kit's own
 * theme is adopted from JavaScript at boot — so the tests that matter are the ones about what the
 * generated bytes actually say, not merely that a generator ran.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  SHEETS,
  commentOf,
  expandRule,
  readSource,
  run,
  sheetCSS,
  tokensCSS,
} from "../scripts/build-styles";

const ROOT = join(import.meta.dir, "..");
const css = readFileSync(join(ROOT, "styles/tokens.css"), "utf8");

describe("the committed stylesheet is what its source means", () => {
  test("both sheets match their sources, which is the gate CI runs", async () => {
    expect(await run(ROOT, false)).toBe(true);
  });

  test("it says it is generated, and names the file to edit instead", () => {
    expect(css).toContain("GENERATED FILE — do not edit.");
    expect(css).toContain("styles/tokens.json");
    expect(css).toContain("styles:sync");
  });
});

describe("what the generated sheet must contain", () => {
  test("three JetBrains Mono faces, each emitted exactly once", () => {
    /* The reason the platform grew an array under a declaration at-rule (spec.md §9.2): an object's
       keys are unique, so one `@font-face` key could state one weight. Before that an array emitted
       NOTHING, so the assertion that matters is the count. */
    expect(css.match(/@font-face \{/g)?.length).toBe(3);
    for (const weight of ["400", "500", "700"]) {
      expect(css, weight).toContain(`url("../fonts/jetbrains-mono-${weight}.woff2")`);
      expect(css.match(new RegExp(`jetbrains-mono-${weight}\\.woff2`, "g"))?.length).toBe(1);
    }
    // Relative to `styles/`, which is where this file is and why it may not move.
    expect(css).not.toContain('url("fonts/');
  });

  test("the panel widths are on :root, where the resize logic writes them", () => {
    /* `panel-resize.ts` writes these as inline styles on `document.documentElement`. A declaration
       on any closer ancestor of #app would shadow that inline override and freeze the sidebars, so
       the ONLY correct home is the root rule. */
    const root = css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {")));
    expect(root).toContain("--panel-w-left: 240px;");
    expect(root).toContain("--panel-w-right: 280px;");
  });

  test("the reset reaches the root element as well as everything under it", () => {
    /* `*` matched `html`; `:root *` does not. The two declarations are therefore written twice on
       purpose — once on the root, once on its descendants — and dropping the root half would leave
       `html` with a box-sizing the rest of the page does not have. */
    expect(css).toContain(":root *,\n:root *::before,\n:root *::after {");
    const root = css.slice(css.indexOf(":root {"), css.indexOf("}", css.indexOf(":root {")));
    expect(root).toContain("box-sizing: border-box;");
    expect(root).toContain("margin: 0;");
  });

  test("the shell fills the viewport and the light boot has its own backdrop", () => {
    expect(css).toContain(":root body {");
    expect(css).toContain("background: var(--jx-bg, #111114);");
    expect(css).toContain(':root[data-theme="light"],\n:root[data-theme="light"] body {');
    expect(css).toContain("background: var(--jx-bg, #f7f7f9);");
  });

  test("every semantic token is an alias of a kit token, with a hex fallback", () => {
    // What `check-styles.ts` reads to hold the guidelines table; the shape is load-bearing for it.
    for (const [token, kit] of [
      ["--bg", "--jx-bg"],
      ["--fg", "--jx-fg"],
      ["--accent", "--jx-accent"],
      ["--radius", "--jx-radius-sm"],
    ]) {
      expect(css, token).toContain(`${token}: var(${kit}, `);
    }
  });

  test("no Spectrum name survives here — those live in the file with a death date", () => {
    expect(css).not.toContain("--spectrum-");
    expect(css).not.toContain("sp-theme");
    const spectrum = readFileSync(join(ROOT, "styles/spectrum.css"), "utf8");
    expect(spectrum).toContain("sp-theme {");
    expect(spectrum).toContain("--spectrum-");
  });
});

describe("expandRule", () => {
  test("puts one declaration on each line", () => {
    expect(expandRule(":root { a: 1; b: 2 }")).toBe(":root {\n  a: 1;\n  b: 2;\n}");
  });

  test("puts one selector on each line, which is the shape oxfmt would impose anyway", () => {
    /* Not cosmetic: `bun run format` rewrites every tracked `.css`, so a generator emitting any
       other shape is undone by the next format and leaves the gate red with nothing wrong. */
    expect(expandRule("a, b::before { c: 1 }")).toBe("a,\nb::before {\n  c: 1;\n}");
    // A comma inside `:is()` separates nothing, so the splitter has to be selector-aware.
    expect(expandRule(":is(a, b) c { d: 1 }")).toBe(":is(a, b) c {\n  d: 1;\n}");
  });

  test("a semicolon inside quotes or parentheses is part of a value", () => {
    /* The reason this is written rather than a `split(";")`: a font stack and a `color-mix()` both
       carry punctuation, and breaking one produces a declaration that parses as nothing. */
    expect(expandRule(`:root { --f: "a;b"; --g: 1 }`)).toBe(`:root {\n  --f: "a;b";\n  --g: 1;\n}`);
    expect(expandRule(":root { --c: color-mix(in oklab, a 6%, b); --d: 2 }")).toBe(
      ":root {\n  --c: color-mix(in oklab, a 6%, b);\n  --d: 2;\n}",
    );
  });

  test("leaves a rule with no body, and text that is no rule, alone", () => {
    expect(expandRule(":root { }")).toBe(":root {\n}");
    expect(expandRule("/* a comment */")).toBe("/* a comment */");
  });
});

describe("the source", () => {
  test("is a style block the builder reads, and the fonts are a list", async () => {
    const style = await readSource(ROOT);
    expect(Array.isArray(style["@font-face"])).toBe(true);
    expect((style["@font-face"] as unknown[]).length).toBe(3);
  });

  test("a change to the source changes the output, which is what the gate compares", () => {
    const before = tokensCSS({ color: "red" });
    const after = tokensCSS({ color: "blue" });
    expect(before).not.toBe(after);
    expect(after).toContain("color: blue;");
  });
});

const forced = readFileSync(join(ROOT, "styles/forced-colors.css"), "utf8");

describe("the forced-colours sheet", () => {
  test("its rules are UNSCOPED, so each reaches the elements it always did", () => {
    /* `:root` is right for the token layer and wrong here: a `.pane-tab` key under `:root` resolves
       to `:root.pane-tab`, which matches nothing, because a class key compounds onto its scope. */
    expect(forced).not.toContain(":root.");
    expect(forced).not.toContain(":root ");
    for (const selector of ['.pane-tab[aria-selected="true"]', ":focus-visible", ".artboard"]) {
      expect(forced, selector).toContain(selector);
    }
  });

  test("every affordance the mode deletes is redrawn, with a system colour", () => {
    // Each pair is one affordance from the file's own list: what vanishes, and what replaces it.
    const cases: [string, string][] = [
      [".tab--active", "border-bottom: 2px solid Highlight;"],
      [".problem-row", "border-left: 2px solid Highlight;"],
      [".is-drop-target", "outline: 3px solid Highlight;"],
      [":focus-visible", "outline: 2px solid Highlight;"],
      [".severity-dot", "border: 1px solid CanvasText;"],
      ['[aria-disabled="true"]', "color: GrayText;"],
    ];
    for (const [what, redrawn] of cases) {
      expect(forced, what).toContain(what);
      expect(forced, redrawn).toContain(redrawn);
    }
    // The artboard opts OUT, because it renders the reader's own document rather than the chrome.
    expect(forced).toContain("forced-color-adjust: none;");
  });

  test("every rule sits inside the forced-colours query and nowhere else", () => {
    /* A rule that escaped the query would repaint the ordinary UI. The builder emits one wrapper
       per rule rather than one around all of them — valid CSS and the same condition either way —
       so the count is the check that none slipped out. */
    const rules = forced.match(/^ {2}[^ @}].*\{$/gm) ?? [];
    expect(forced.match(/@media \(forced-colors: active\) \{/g)?.length).toBe(7);
    expect(rules.length).toBe(7);
  });

  test("every rule carries the reasoning that was written beside it", () => {
    /* The point of `$description`. The sentences in the stylesheet this replaced are the most
       valuable thing in it, and a migration that moved the declarations and dropped the reasoning
       would be a loss no gate could see. */
    expect(forced.match(/^\/\* /gm)?.length).toBeGreaterThanOrEqual(7);
    // Whitespace-collapsed, because a wrapped comment breaks a sentence across lines by design.
    const prose = forced.replaceAll(/\s+/g, " ");
    for (const phrase of [
      "box-shadow: inset",
      "invisible here twice over",
      "palette's own focus colour",
      "USER'S OWN DOCUMENT",
      "whole meaning is its fill",
      "Opacity is not a colour",
    ]) {
      expect(prose, phrase).toContain(phrase);
    }
  });
});

describe("commentOf", () => {
  test("wraps prose and indents its continuation under the opener", () => {
    const long = "word ".repeat(40).trim();
    const out = commentOf(long);
    expect(out.startsWith("/* ")).toBe(true);
    expect(out.endsWith(" */")).toBe(true);
    for (const line of out.split("\n")) {
      expect(line.length).toBeLessThanOrEqual(100);
    }
    expect(
      out
        .split("\n")
        .slice(1)
        .every((line) => line.startsWith("   ")),
    ).toBe(true);
  });

  test("a short reason stays on one line", () => {
    expect(commentOf("short reason")).toBe("/* short reason */");
  });
});

describe("expandRule on a wrapper", () => {
  test("expands the rule INSIDE a query rather than reading it as a declaration", () => {
    /* It used to split on the outermost braces only, so an inner rule was read as one declaration
       — semicolon and all — and emitted `@media (…) { .a { … }; }`, with its selector list never
       split. */
    expect(expandRule("@media (x) { .a, .b { c: 1; d: 2 } }")).toBe(
      "@media (x) {\n  .a,\n  .b {\n    c: 1;\n    d: 2;\n  }\n}",
    );
  });

  test("expands every stop of a keyframes block", () => {
    expect(expandRule("@keyframes n { from { opacity: 0 } to { opacity: 1 } }")).toBe(
      "@keyframes n {\n  from {\n    opacity: 0;\n  }\n  to {\n    opacity: 1;\n  }\n}",
    );
  });

  test("a brace inside a value closes nothing", () => {
    expect(expandRule(`a { content: "{" }`)).toBe(`a {\n  content: "{";\n}`);
  });
});

describe("sheetCSS", () => {
  test("puts a block's $description above the rule it explains", () => {
    expect(sheetCSS({ $description: "why", color: "red" } as never, ":root", "/* h */")).toBe(
      "/* h */\n/* why */\n:root {\n  color: red;\n}\n",
    );
  });

  test("a block with no prose gets no comment", () => {
    expect(sheetCSS({ color: "red" } as never, ":root", "/* h */")).toBe(
      "/* h */\n:root {\n  color: red;\n}\n",
    );
  });
});

describe("a generated sheet has one author", () => {
  test("every generated output is excluded from the formatter", () => {
    /* `bun run format` wraps a declaration at its own print width and the generator does not, so a
       generated sheet the formatter also owns gets rewritten by each in turn — `styles:check` red
       with nothing wrong. The two lists are held equal here because a sheet added to one and not
       the other fails that way rather than obviously. */
    const config = JSON.parse(readFileSync(join(ROOT, "../../.oxfmtrc.json"), "utf8")) as {
      ignorePatterns: string[];
    };
    for (const sheet of SHEETS) {
      expect(config.ignorePatterns, sheet.output).toContain(`packages/studio/${sheet.output}`);
    }
  });

  test("each generated sheet is linked, in the order the cascade needs", () => {
    // A sheet nobody links is the 2.1.0 dead-links outage; check-studio-package.ts owns the set.
    const html = readFileSync(join(ROOT, "index.html"), "utf8");
    for (const sheet of SHEETS) {
      expect(html, sheet.output).toContain(`./${sheet.output}`);
    }
    expect(html.indexOf("shell-frame.css")).toBeLessThan(html.indexOf("shell.css"));
    expect(html.indexOf("forced-colors.css")).toBeGreaterThan(html.indexOf("shell.css"));
  });
});

const frame = readFileSync(join(ROOT, "styles/shell-frame.css"), "utf8");

describe("the shell frame", () => {
  test("the grid names its columns, and the dock track is declared on :root", () => {
    /* The names, because every rule addressed the columns by index and a name survives an
       insertion. The `:root` track, because `shell.ts`'s applyDockLayout writes it inline on the
       root element and any closer ancestor would shadow that — and because an UNSET custom property
       inside the `grid-template-rows` shorthand invalidates the whole declaration, so the shell
       would paint one frame with no grid at all. */
    expect(frame).toContain("[rail] 56px");
    expect(frame).toContain("[nav] var(--panel-w-left)");
    expect(frame).toContain("[pane] 1fr");
    expect(frame).toContain("[insp] var(--panel-w-right)");
    expect(frame).toContain("--dock-h-bottom: 220px;");
    expect(frame).toContain("grid-template-rows: 36px minmax(0, 1fr) var(--dock-h-bottom) 24px;");
  });

  test("each collapse variant zeroes its track and hides its handle", () => {
    for (const [side, token] of [
      ["left", "--panel-w-left"],
      ["right", "--panel-w-right"],
    ]) {
      expect(frame, side).toContain(`#app.${side}-collapsed {`);
      expect(frame, token).toContain(`${token}: 0px;`);
      expect(frame, side).toContain(`#app.${side}-collapsed #resize-${side}`);
    }
    expect(frame).toContain("#app.bottom-collapsed {");
    expect(frame).toContain("--dock-h-bottom: 0px;");
  });

  test("the four overlay layers keep their stacking order", () => {
    /* The z-indices were inline style attributes once, which put the one piece of ordering the
       whole overlay system depends on outside the reach of the stacking rule. The toast host is
       ABOVE the dialog host because an operation started from a dialog reports its outcome to the
       person still looking at it. */
    const z = (name: string) =>
      Number(new RegExp(`\\.jx-layer--${name} \\{[^}]*z-index: (\\d+)`).exec(frame)?.[1]);
    expect(z("popover")).toBe(1000);
    expect(z("modal")).toBe(2000);
    expect(z("dialog")).toBe(3000);
    expect(z("toast")).toBeGreaterThan(z("dialog"));
    expect(frame).toContain("pointer-events: none;");
  });

  test("the platform's drag region stays a class, because it is a contract and not a look", () => {
    // `commandbar.ts` adds it; the desktop window reads `-webkit-app-region` to move the window.
    expect(frame).toContain("#toolbar.electrobun-webkit-app-region-drag");
    expect(frame).toContain("-webkit-app-region: drag;");
  });

  test("the statusbar owns its own row, below the dock's", () => {
    /* Sharing that row put the whole bar in a zero-height cell — it rendered its three fields into
       nothing while the 24px track stood empty, so the app looked like it had lost its status bar
       the day it gained a dock. */
    const rule = frame.slice(frame.indexOf("#statusbar {"));
    expect(rule.slice(0, rule.indexOf("}"))).toContain("grid-row: 4;");
  });

  test("nothing that moved was left behind, and nothing else came with it", () => {
    const shell = readFileSync(join(ROOT, "styles/shell.css"), "utf8");
    const overlays = readFileSync(join(ROOT, "styles/overlays.css"), "utf8");
    for (const selector of ["#app {", "#toolbar {", "#statusbar {", ".resize-handle {"]) {
      expect(shell, selector).not.toContain(selector);
      expect(frame, selector).toContain(selector);
    }
    expect(overlays).not.toContain(".jx-layer {");
    // The AI chat panel stayed: it is a lit surface, and it moves with its surface, not with this.
    expect(shell).toContain(".ai-chat-header");
  });
});
