/**
 * Emits `dist/_headers` — the response headers the build knows and the host does not.
 *
 * Cacheability in particular is something only the build can decide: it is the thing that chose the
 * filenames, so it is the only party that knows which of them embed a content hash and are
 * therefore safe to cache forever. Left unsaid, every host applies its own default to output whose
 * lifetime it cannot see (RFC 9111).
 *
 * Pure except for `writeHeaders`, which is the one function that touches disk.
 *
 * @docs framework/site/deployment
 */

import { withBase } from "@jxsuite/schema/asset-paths";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildCspHeaders, normalizeCspConfig } from "./csp.ts";
import type { CspSources } from "./csp.ts";
import type { HeadersConfig, ProjectConfig } from "@jxsuite/schema/types";

/** One `_headers` stanza: a path pattern and the headers it sets. */
export interface HeaderRule {
  pattern: string;
  headers: Record<string, string>;
}

/**
 * The only content-addressed output the build produces. `variantFilename()` embeds an 8-character
 * digest of the source bytes, so a changed image is a changed URL and the old one can be cached
 * forever (RFC 8246).
 */
export const IMMUTABLE_PATTERN = "/images/_optimized/*";

/** A year, the conventional ceiling for `max-age`. */
const IMMUTABLE_MAX_AGE = 31_536_000;

/**
 * Paths that must NEVER be marked immutable, asserted by a test.
 *
 * `/components/<tag>.js` and `/assets/<slug>.js` are named after the thing they contain, not after
 * its content — editing a component reuses the URL. Marking either immutable is a year-long cache
 * poisoning bug that only appears for visitors who came before the edit, which is the worst
 * possible shape for one. Making them cacheable means content-hashing them first.
 */
export const NEVER_IMMUTABLE = ["/components/*", "/assets/*"] as const;

const BANNER = "# Generated by @jxsuite/compiler — configure via build.headers in project.json.";
const AUTHOR_BANNER =
  "# ─── public/_headers (hand-authored; these rules override the block above) ───";

/**
 * The generated rules, general first. Order matters: on both Cloudflare and Netlify a later
 * matching rule wins for a duplicate header name, so the specific `immutable` stanza must follow
 * the catch-all that revalidates.
 */
export function buildHeaderRules(
  build: ProjectConfig["build"],
  cspSources?: CspSources,
): {
  rules: HeaderRule[];
  errors: string[];
} {
  const cfg: HeadersConfig = build?.headers ?? {};
  const errors: string[] = [];
  if (cfg.enabled === false) {
    return { errors, rules: [] };
  }

  const security = cfg.security ?? {};
  const wide: Record<string, string> = {};

  if (security.contentTypeOptions !== false) {
    wide["X-Content-Type-Options"] = "nosniff";
  }
  if (security.referrerPolicy !== false) {
    wide["Referrer-Policy"] = security.referrerPolicy ?? "strict-origin-when-cross-origin";
  }
  if (security.permissionsPolicy !== false) {
    wide["Permissions-Policy"] =
      security.permissionsPolicy ?? "camera=(), microphone=(), geolocation=()";
  }
  if (security.frameOptions !== false) {
    wide["X-Frame-Options"] = security.frameOptions ?? "SAMEORIGIN";
  }

  const { hsts } = security;
  if (hsts) {
    const opts = hsts === true ? {} : hsts;
    const maxAge = opts.maxAge ?? IMMUTABLE_MAX_AGE;
    const includeSubDomains = opts.includeSubDomains ?? true;
    const preload = opts.preload ?? false;
    if (preload && !includeSubDomains) {
      /*
       * Submission to the preload list REQUIRES includeSubDomains. Emitting the header anyway
       * produces something that looks submitted and is not, which is worse than not emitting it.
       */
      errors.push(
        "build.headers.security.hsts: `preload` requires `includeSubDomains` — the preload list " +
          "will not accept the header without it.",
      );
    } else {
      wide["Strict-Transport-Security"] = [
        `max-age=${maxAge}`,
        includeSubDomains ? "includeSubDomains" : null,
        preload ? "preload" : null,
      ]
        .filter(Boolean)
        .join("; ");
    }
  }

  /*
   * One policy for the whole site, from the inline scripts and external origins the build actually
   * emitted. It goes in the `/*` stanza rather than per page because the hashes are constants —
   * and because a per-page policy would exhaust the host's rule budget on any real site.
   */
  const cspConfig = normalizeCspConfig(security);
  if (cspConfig) {
    if (cspSources === undefined) {
      errors.push(
        "build.headers.security.csp is set, but no page was scanned for inline scripts — the " +
          "policy would block every one of them.",
      );
    } else {
      Object.assign(wide, buildCspHeaders(cspSources, cspConfig));
    }
  }

  const cache = cfg.cache ?? "auto";
  if (cache === "auto") {
    /*
     * Everything else — HTML at `/about/`, component JS and CSS, the sitemap, the feed — revalidates
     * every time. The ETag makes that cheap, and it is the only correct default for output whose URL
     * does not change when its content does.
     */
    wide["Cache-Control"] = "public, max-age=0, must-revalidate";
  }

  const rules: HeaderRule[] = [];
  if (Object.keys(wide).length > 0) {
    rules.push({ headers: wide, pattern: "/*" });
  }
  if (cache === "auto") {
    rules.push({
      headers: { "Cache-Control": `public, max-age=${IMMUTABLE_MAX_AGE}, immutable` },
      pattern: IMMUTABLE_PATTERN,
    });
  }
  for (const [pattern, headers] of Object.entries(cfg.rules ?? {})) {
    rules.push({ headers, pattern });
  }
  return { errors, rules };
}

/**
 * Content-Type rules for output whose extension no host maps.
 *
 * `.xml` is served as `application/xml` and `.json` as `application/json` by default, which is not
 * wrong but is not what a feed reader looks for. Only files that actually exist get a rule, so the
 * emitted block never describes output this build did not produce.
 */
export function contentTypeRules(outDir: string): HeaderRule[] {
  const known: [string, string][] = [
    ["feed.xml", "application/atom+xml; charset=utf-8"],
    ["feed.json", "application/feed+json; charset=utf-8"],
    ["manifest.webmanifest", "application/manifest+json; charset=utf-8"],
    [".well-known/security.txt", "text/plain; charset=utf-8"],
  ];
  const rules: HeaderRule[] = [];
  for (const [name, type] of known) {
    if (existsSync(join(outDir, name))) {
      rules.push({ headers: { "Content-Type": type }, pattern: `/${name}` });
    }
  }
  // The RFC 5005 archives share the feed's type.
  if (existsSync(join(outDir, "feed", "archive"))) {
    rules.push({
      headers: { "Content-Type": "application/atom+xml; charset=utf-8" },
      pattern: "/feed/archive/*",
    });
  }
  return rules;
}

/**
 * Re-root every rule's pattern onto the deployment base.
 *
 * A `_headers` pattern is matched against the REQUEST path, so on a site served from `/m/my-site/`
 * a rule for `/assets/*` matches nothing at all — which is silent, because a missing cache header
 * is a slow site rather than a broken one. The generated patterns and the author's `build.headers`
 * rules go through together: both describe the same URL space.
 *
 * @param {readonly HeaderRule[]} rules
 * @param {string} base - From `siteBasePath`; `""` returns the rules untouched
 * @returns {HeaderRule[]}
 */
export function rebaseHeaderRules(rules: readonly HeaderRule[], base: string): HeaderRule[] {
  if (base === "") {
    return [...rules];
  }
  return rules.map((rule) => ({ headers: rule.headers, pattern: withBase(base, rule.pattern) }));
}

/** Render rules in the Netlify / Cloudflare Pages `_headers` format. */
export function renderHeaders(rules: readonly HeaderRule[]): string {
  const blocks = rules.map((rule) => {
    const lines = Object.entries(rule.headers).map(([name, value]) => `  ${name}: ${value}`);
    return [rule.pattern, ...lines].join("\n");
  });
  return `${[BANNER, "", ...blocks].join("\n")}\n`;
}

/**
 * Write `dist/_headers`, preserving a hand-authored `public/_headers` **below** the generated
 * block.
 *
 * `ensureRobotsSitemap` appends for the same reason this prepends: both run after the `public/`
 * copy so they edit the deployed file, but a later `_headers` rule wins for a duplicate header
 * name, so the author's block has to come last to override.
 *
 * The author's file is concatenated verbatim rather than merged. Both platforms have removal (`!
 * Header-Name`) and conditional (`Language=`, `Country=`) extensions, and a structural merge would
 * silently drop whatever it could not parse — deferring to each platform's own documented
 * precedence is both simpler and more correct.
 */
export function writeHeaders(outDir: string, rules: readonly HeaderRule[]): number {
  if (rules.length === 0) {
    return 0;
  }
  const path = join(outDir, "_headers");
  const authored = existsSync(path) ? readFileSync(path, "utf8").trim() : "";
  const generated = renderHeaders(rules);
  const body = authored === "" ? generated : `${generated}\n${AUTHOR_BANNER}\n${authored}\n`;
  writeFileSync(path, body, "utf8");
  return 1;
}

/**
 * Write `dist/.nojekyll`.
 *
 * GitHub Pages runs Jekyll, which excludes every `_`-prefixed path — which is `_headers`,
 * `_redirects`, `_worker.js`, `_routes.json` and `_islands/`. One empty file closes the whole class
 * of "works locally, half-broken on Pages", so it is unconditional rather than an adapter option.
 */
export function writeNoJekyll(outDir: string): number {
  const path = join(outDir, ".nojekyll");
  if (existsSync(path)) {
    return 0;
  }
  writeFileSync(path, "", "utf8");
  return 1;
}
