[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/tests/**",
  "./result/**",
  "../auth/**",
  "../connector/**",
  "../parser/**",
  "../../packages/**",
]
coverageThreshold = { lines = 0.99, functions = 0.99 }
