/**
 * Compile-server.js — Hono server handler compilation
 *
 * Compiles `timing: "server"` entries from a Jx document into a deployable Hono server handler
 * file.
 */

import { withBase } from "@jxsuite/schema/asset-paths";
import { dereference } from "@apidevtools/json-schema-ref-parser";
import { collectServerEntries } from "../shared.ts";
import { localeNegotiationMiddleware } from "../site/locale-negotiation.ts";
import type { ResolvedI18n } from "../site/i18n.ts";
import type { JxElement } from "@jxsuite/schema/types";

/**
 * Compile a Jx document to a Hono server handler file. The handler exposes each `timing: "server"`
 * entry as a POST endpoint under `/_jx/server/$export`. Returns null if no server entries are
 * found.
 *
 * @example
 *   const server = await compileServer("./dashboard.json");
 *   if (server) fs.writeFileSync("dist/server.js", server);
 *
 * @param {string | object} sourcePath - Path to .json file, URL, or raw object
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @returns {Promise<string | null>} Hono server handler source string, or null
 */
export async function compileServer(
  sourcePath: string | object,
  opts: {
    baseUrl?: string;
  } = {},
) {
  const { baseUrl = "/_jx/server" } = opts;
  const doc = (await dereference(sourcePath)) as JxElement;
  const entries = collectServerEntries(doc);
  if (entries.length === 0) {
    return null;
  }

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const routes = entries.map(({ exportName }) => buildRoute(exportName, baseUrl)).join("\n");

  return `// Generated by @jxsuite/compiler — do not edit manually
// Deploy as a Cloudflare Worker, Node server, or Bun process.
// Requires: npm install hono

import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}

export default app
`;
}

/**
 * One extension server mount to emit into the generated worker (specs/extensions.md §11). The
 * module is imported statically (Workers cannot dynamic-import), the options are inlined JSON
 * (identifiers only — never secrets), and every mount shares one context object, called in
 * ascending `order`.
 */
export interface SiteMountSpec {
  /** Export name of the mount class (the descriptor title, e.g. "Data"). */
  className: string;
  /** Bare module specifier the worker imports (`server.module`). */
  module: string;
  /** Route subtree the mount owns (`server.basePath`). */
  basePath: string;
  /** Mount order (`server.order`, ascending). */
  order: number;
  /** JSON-inlined mount options (project sections manifest etc.). */
  options: Record<string, unknown>;
}

/** A connector provider class the worker imports and hands to mounts via `options.connectors`. */
export interface SiteConnectorSpec {
  /** The `connector.provider` id (options.connectors key). */
  provider: string;
  /** Export name of the provider implementation (the descriptor title). */
  className: string;
  /** Bare module specifier (`connector.module`). */
  module: string;
}

/**
 * Generate a bundled Hono server entry from pre-collected server entries across an entire site.
 * Used when `build.adapter` is set in project.json. Returns null if no entries or mounts are
 * provided.
 *
 * @param {{ exportName: string; src: string }[]} entries - Resolved server entries
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @param {string | null} [opts.adapter] - Deployment adapter: `"cloudflare-workers"`,
 *   `"cloudflare-pages"`, `"node"`, `"bun"`
 * @param {SiteMountSpec[]} [opts.mounts] - Extension server mounts, already sorted by order
 * @param {SiteConnectorSpec[]} [opts.connectors] - Connector classes used by the mounts
 * @param {ResolvedI18n | null} [opts.i18n] - Locale routing; drives the `/` negotiation middleware
 * @returns {string | null} Complete worker/server source string, or null
 */
export function compileSiteServer(
  entries: { exportName: string; src: string }[],
  opts: {
    baseUrl?: string;
    adapter?: string | null;
    mounts?: SiteMountSpec[];
    connectors?: SiteConnectorSpec[];
    i18n?: ResolvedI18n | null;
    base?: string;
  } = {},
) {
  const { adapter = null, mounts = [], connectors = [], i18n = null, base = "" } = opts;
  /*
   * Routes are registered under the deployment base (`site/base-path.ts`), because the worker IS
   * the origin: the request it sees is the one the visitor's browser sent, and on a site served
   * from `/m/my-site/` that path carries the prefix. A route left at the bare path would simply
   * never match — the 404 nobody attributes to a config value.
   *
   * The dev server takes the opposite approach and strips the base at the edge (`server.ts`), so
   * everything behind it routes on the bare path. Each is internally consistent: production serves
   * exactly one URL space, while `jx dev` deliberately answers both.
   */
  const baseUrl = withBase(base, opts.baseUrl ?? "/_jx/server");
  if (entries.length === 0 && mounts.length === 0 && !adapter) {
    return null;
  }

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const mountBlock = buildMountBlock(mounts, connectors);

  const routes = entries.map(({ exportName }) => buildRoute(exportName, baseUrl)).join("\n");

  // Workers static assets and Pages advanced mode (_worker.js) both route every request
  // Through the worker — unmatched paths must fall through to the ASSETS binding.
  const adapterBlock =
    adapter === "cloudflare-workers" || adapter === "cloudflare-pages"
      ? "\napp.all('*', (c) => c.env.ASSETS.fetch(c.req.raw))\n"
      : "\n";

  /*
   * Negotiation is middleware and it is registered FIRST, before any route and before the ASSETS
   * fallthrough. It has to be: on `/` it either redirects or hands the request straight back to
   * whatever would have served it, and it cannot do the second from behind a terminal handler.
   */
  const localeBlock = localeNegotiationMiddleware(i18n);

  return `// Generated by @jxsuite/compiler — do not edit manually
import { Hono } from 'hono'
${imports}${mountBlock.imports}

const app = new Hono()
${localeBlock}${mountBlock.routes}${routes}
${adapterBlock}
export default app
`;
}

/**
 * Emit the extension-mount section: static imports, one shared ctx, ordered `mount()` calls at
 * module init (top-level await), and `app.all('<basePath>/*', …)` wrappers registered BEFORE the
 * /_jx/server routes and the ASSETS fallthrough.
 *
 * @param {SiteMountSpec[]} mounts
 * @param {SiteConnectorSpec[]} connectors
 * @returns {{ imports: string; routes: string }}
 */
function buildMountBlock(mounts: SiteMountSpec[], connectors: SiteConnectorSpec[]) {
  if (mounts.length === 0) {
    return { imports: "", routes: "" };
  }
  const ordered = mounts.toSorted((a, b) => a.order - b.order);

  const importLines: string[] = [];
  for (const mount of ordered) {
    importLines.push(`import { ${mount.className} } from '${mount.module}'`);
  }
  for (const connector of connectors) {
    importLines.push(`import { ${connector.className} } from '${connector.module}'`);
  }

  const lines: string[] = [
    "// Extension server mounts (specs/extensions.md §11): one shared ctx, mounted in order.",
    "const jxCtx = {}",
    `const jxConnectors = { ${connectors
      .map((c) => `${JSON.stringify(c.provider)}: ${c.className}`)
      .join(", ")} }`,
  ];
  for (const [index, mount] of ordered.entries()) {
    const optionsJson = JSON.stringify(mount.options);
    lines.push(
      `const jxMount${index} = await ${mount.className}.mount({ ...${optionsJson}, connectors: jxConnectors }, jxCtx)`,
      `app.all('${mount.basePath}/*', (c) => jxMount${index}(c.req.raw, c.env))`,
      `app.all('${mount.basePath}', (c) => jxMount${index}(c.req.raw, c.env))`,
    );
  }

  return { imports: `\n${importLines.join("\n")}`, routes: `${lines.join("\n")}\n` };
}

/** @param {string} exportName @param {string} baseUrl */
function buildRoute(exportName: string, baseUrl: string) {
  return `
app.post('${baseUrl}/${exportName}', async (c) => {
  const args = await c.req.json().catch(() => ({}))
  try {
    return c.json(await ${exportName}(args, c.env))
  } catch (e) {
    return c.json({ ok: false, error: e?.message ?? 'Server error' }, 500)
  }
})`;
}
