import { describe, test, expect } from "bun:test";
import { compileClassJson } from "../src/targets/compile-class.js";

// ─── compileClassJson — Basic class generation ──────────────────────────────

describe("compileClassJson — basic", () => {
  test("throws when title is missing", () => {
    expect(() => compileClassJson({ $prototype: "Class" })).toThrow("missing title");
  });

  test("generates class declaration with title", () => {
    const result = compileClassJson({ $prototype: "Class", title: "Foo" });
    expect(result).toContain("class Foo {");
    expect(result).toContain("export { Foo };");
    expect(result).toContain("export default Foo;");
  });

  test("includes generation comment", () => {
    const result = compileClassJson({ $prototype: "Class", title: "Bar" });
    expect(result).toContain("// Generated by @jxplatform/compiler");
  });

  test("includes $id as source comment", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Bar",
      $id: "https://example.com/Bar.class.json",
    });
    expect(result).toContain("// Source: https://example.com/Bar.class.json");
  });

  test("no $id omits source comment", () => {
    const result = compileClassJson({ $prototype: "Class", title: "Baz" });
    expect(result).not.toContain("// Source:");
  });
});

// ─── compileClassJson — extends ─────────────────────────────────────────────

describe("compileClassJson — extends", () => {
  test("no extends generates plain class", () => {
    const result = compileClassJson({ $prototype: "Class", title: "Foo" });
    expect(result).toContain("class Foo {");
    expect(result).not.toContain("extends");
  });

  test("string extends generates extends clause", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      extends: "HTMLElement",
    });
    expect(result).toContain("class Foo extends HTMLElement {");
  });

  test("extends Object is treated as no extends", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      extends: "Object",
    });
    expect(result).toContain("class Foo {");
    expect(result).not.toContain("extends Object");
  });

  test("$ref extends extracts class name from filename", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Child",
      extends: { $ref: "./Parent.class.json" },
    });
    expect(result).toContain("class Child extends Parent {");
  });

  test("$ref with unrecognized pattern falls back to Object", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Child",
      extends: { $ref: "./weird" },
    });
    expect(result).toContain("class Child {");
    expect(result).not.toContain("extends");
  });

  test("extends as unknown object type falls back to Object", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Child",
      extends: { something: "else" },
    });
    expect(result).toContain("class Child {");
  });

  test("super() call emitted for non-Object base", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      extends: "HTMLElement",
    });
    expect(result).toContain("super();");
  });

  test("super() with arguments from superCall", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      extends: "Base",
      $defs: {
        constructor: {
          role: "constructor",
          $prototype: "Function",
          superCall: { arguments: ["config.a", "config.b"] },
        },
      },
    });
    expect(result).toContain("super(config.a, config.b);");
  });
});

// ─── compileClassJson — fields ──────────────────────────────────────────────

describe("compileClassJson — fields", () => {
  test("public instance field with default", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          name: {
            role: "field",
            access: "public",
            scope: "instance",
            identifier: "name",
            default: "untitled",
          },
        },
      },
    });
    expect(result).toContain('this.name = config.name !== undefined ? config.name : "untitled"');
  });

  test("private instance field with # prefix", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          secret: {
            role: "field",
            access: "private",
            scope: "instance",
            identifier: "secret",
            initializer: 42,
          },
        },
      },
    });
    expect(result).toContain("#secret;");
    expect(result).toContain("this.#secret = config.secret !== undefined ? config.secret : 42");
  });

  test("static field", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          count: {
            role: "field",
            access: "public",
            scope: "static",
            identifier: "count",
            initializer: 0,
          },
        },
      },
    });
    expect(result).toContain("static count = 0;");
  });

  test("static private field", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          instances: {
            role: "field",
            access: "private",
            scope: "static",
            identifier: "instances",
            default: [],
          },
        },
      },
    });
    expect(result).toContain("static #instances = [];");
  });

  test("field uses key as identifier fallback", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          myField: {
            role: "field",
            access: "public",
            scope: "instance",
          },
        },
      },
    });
    expect(result).toContain("this.myField = config.myField");
  });

  test("field with no initializer or default uses null", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          val: {
            role: "field",
            access: "public",
            scope: "instance",
            identifier: "val",
          },
        },
      },
    });
    expect(result).toContain("config.val !== undefined ? config.val : null");
  });

  test("initializer takes precedence over default for static fields", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        fields: {
          x: {
            role: "field",
            scope: "static",
            access: "public",
            identifier: "x",
            initializer: 10,
            default: 5,
          },
        },
      },
    });
    expect(result).toContain("static x = 10;");
  });
});

// ─── compileClassJson — constructor ─────────────────────────────────────────

describe("compileClassJson — constructor", () => {
  test("constructor body as string", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        constructor: {
          role: "constructor",
          $prototype: "Function",
          body: "this.ready = true;",
        },
      },
    });
    expect(result).toContain("this.ready = true;");
  });

  test("constructor body as array", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        constructor: {
          role: "constructor",
          $prototype: "Function",
          body: ["this.a = 1;", "this.b = 2;"],
        },
      },
    });
    expect(result).toContain("this.a = 1;");
    expect(result).toContain("this.b = 2;");
  });
});

// ─── compileClassJson — methods ─────────────────────────────────────────────

describe("compileClassJson — methods", () => {
  test("instance method with body", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          greet: {
            role: "method",
            access: "public",
            scope: "instance",
            identifier: "greet",
            parameters: [{ identifier: "name" }],
            body: 'return "Hello " + name;',
          },
        },
      },
    });
    expect(result).toContain("greet(name) {");
    expect(result).toContain('return "Hello " + name;');
  });

  test("static method", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          create: {
            role: "method",
            access: "public",
            scope: "static",
            identifier: "create",
            body: "return new Foo();",
          },
        },
      },
    });
    expect(result).toContain("static create() {");
  });

  test("private method", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          internal: {
            role: "method",
            access: "private",
            scope: "instance",
            identifier: "internal",
            body: "return this.#data;",
          },
        },
      },
    });
    expect(result).toContain("#internal() {");
  });

  test("async method detected from await keyword", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          fetch: {
            role: "method",
            identifier: "fetch",
            body: "const r = await fetch(this.url); return r.json();",
          },
        },
      },
    });
    expect(result).toContain("async fetch() {");
  });

  test("async method detected from returnType containing Promise", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          load: {
            role: "method",
            identifier: "load",
            returnType: { $ref: "#/$defs/returnTypes/Promise" },
            body: "return this.data;",
          },
        },
      },
    });
    expect(result).toContain("async load() {");
  });

  test("method body as array of lines", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          multi: {
            role: "method",
            identifier: "multi",
            body: ["const a = 1;", "return a + 2;"],
          },
        },
      },
    });
    expect(result).toContain("const a = 1;");
    expect(result).toContain("return a + 2;");
  });

  test("method with no body generates empty body", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          noop: {
            role: "method",
            identifier: "noop",
          },
        },
      },
    });
    expect(result).toContain("noop() {");
  });

  test("method uses key as identifier fallback", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          doStuff: {
            role: "method",
            body: "return true;",
          },
        },
      },
    });
    expect(result).toContain("doStuff() {");
  });

  test("parameters resolved from $ref", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          process: {
            role: "method",
            identifier: "process",
            parameters: [
              { $ref: "#/$defs/parameters/input" },
              { $ref: "#/$defs/parameters/options" },
            ],
            body: "return input;",
          },
        },
      },
    });
    expect(result).toContain("process(input, options) {");
  });

  test("parameters resolved from name fallback", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          go: {
            role: "method",
            identifier: "go",
            parameters: [{ name: "x" }],
            body: "return x;",
          },
        },
      },
    });
    expect(result).toContain("go(x) {");
  });

  test("parameter fallback to 'arg'", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          go: {
            role: "method",
            identifier: "go",
            parameters: [{}],
            body: "return arg;",
          },
        },
      },
    });
    expect(result).toContain("go(arg) {");
  });
});

// ─── compileClassJson — accessors ───────────────────────────────────────────

describe("compileClassJson — accessors", () => {
  test("getter accessor", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          fullName: {
            role: "accessor",
            identifier: "fullName",
            getter: { body: "return this.first + ' ' + this.last;" },
          },
        },
      },
    });
    expect(result).toContain("get fullName() {");
    expect(result).toContain("return this.first + ' ' + this.last;");
  });

  test("setter accessor", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          value: {
            role: "accessor",
            identifier: "value",
            setter: {
              parameters: [{ identifier: "v" }],
              body: "this._value = v;",
            },
          },
        },
      },
    });
    expect(result).toContain("set value(v) {");
    expect(result).toContain("this._value = v;");
  });

  test("getter + setter accessor", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          count: {
            role: "accessor",
            identifier: "count",
            getter: { body: "return this._count;" },
            setter: {
              parameters: [{ identifier: "v" }],
              body: "this._count = v;",
            },
          },
        },
      },
    });
    expect(result).toContain("get count() {");
    expect(result).toContain("set count(v) {");
  });

  test("static accessor", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          instance: {
            role: "accessor",
            scope: "static",
            identifier: "instance",
            getter: { body: "return Foo._inst;" },
          },
        },
      },
    });
    expect(result).toContain("static get instance() {");
  });

  test("setter with $ref parameters", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          val: {
            role: "accessor",
            identifier: "val",
            setter: {
              parameters: [{ $ref: "#/$defs/parameters/newVal" }],
              body: "this._val = newVal;",
            },
          },
        },
      },
    });
    expect(result).toContain("set val(newVal) {");
  });

  test("setter with no parameters defaults to 'v'", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Foo",
      $defs: {
        methods: {
          val: {
            role: "accessor",
            identifier: "val",
            setter: { body: "this._val = v;" },
          },
        },
      },
    });
    // No parameters array → resolveParams returns empty string
    expect(result).toContain("set val() {");
  });
});

// ─── compileClassJson — full integration ────────────────────────────────────

describe("compileClassJson — full integration", () => {
  test("compiles MarkdownFile-style class", () => {
    const classDef = {
      $prototype: "Class",
      title: "MarkdownFile",
      $implementation: "./md.js",
      $defs: {
        parameters: {
          src: { identifier: "src", type: { type: "string" } },
          directives: { identifier: "directives", type: { type: "boolean", default: false } },
        },
        fields: {
          config: {
            role: "field",
            access: "private",
            scope: "instance",
            identifier: "config",
            type: { type: "object" },
          },
        },
        constructor: {
          role: "constructor",
          $prototype: "Function",
          parameters: [{ $ref: "#/$defs/parameters/src" }],
          body: ["this.config = config;"],
        },
        methods: {
          resolve: {
            role: "method",
            access: "public",
            scope: "instance",
            identifier: "resolve",
            body: "return this.config;",
          },
        },
      },
    };

    const result = compileClassJson(classDef);
    expect(result).toContain("class MarkdownFile {");
    expect(result).toContain("#config;");
    expect(result).toContain("this.#config = config.config");
    expect(result).toContain("this.config = config;");
    expect(result).toContain("resolve() {");
    expect(result).toContain("export { MarkdownFile };");
    expect(result).toContain("export default MarkdownFile;");
  });

  test("compiles class with static + private + async + accessor", () => {
    const result = compileClassJson({
      $prototype: "Class",
      title: "Complex",
      extends: "Base",
      $id: "https://example.com/Complex.class.json",
      $defs: {
        fields: {
          count: { role: "field", access: "public", scope: "static", initializer: 0 },
          data: { role: "field", access: "private", scope: "instance", default: [] },
        },
        constructor: {
          role: "constructor",
          $prototype: "Function",
          superCall: { arguments: [] },
          body: "Complex.count++;",
        },
        methods: {
          load: {
            role: "method",
            identifier: "load",
            body: "const r = await fetch('/api'); this._data = r;",
          },
          size: {
            role: "accessor",
            identifier: "size",
            getter: { body: "return this._data.length;" },
          },
          helper: {
            role: "method",
            access: "private",
            scope: "static",
            identifier: "helper",
            parameters: [{ identifier: "x" }],
            body: "return x * 2;",
          },
        },
      },
    });

    expect(result).toContain("class Complex extends Base {");
    expect(result).toContain("static count = 0;");
    expect(result).toContain("#data;");
    expect(result).toContain("super();");
    expect(result).toContain("Complex.count++;");
    expect(result).toContain("async load() {");
    expect(result).toContain("get size() {");
    expect(result).toContain("static #helper(x) {");
    expect(result).toContain("// Source: https://example.com/Complex.class.json");
  });
});

// ─── compile() routing for $prototype: "Class" ─────────────────────────────

describe("compile — $prototype: Class routing", () => {
  test("routes $prototype: Class to compile-class.js", async () => {
    const { compile } = await import("../src/compiler.js");
    const result = await compile({
      $prototype: "Class",
      title: "TestClass",
    });
    expect(result.html).toBe("");
    expect(result.files).toHaveLength(1);
    expect(result.files[0].content).toContain("class TestClass {");
    expect(result.files[0].content).toContain("export { TestClass };");
  });

  test("output path derived from title for raw object", async () => {
    const { compile } = await import("../src/compiler.js");
    const result = await compile({
      $prototype: "Class",
      title: "MyWidget",
    });
    expect(result.files[0].path).toBe("MyWidget.js");
  });
});
