// Generated by @jxplatform/compiler — do not edit manually
// Source: components/task-stats.json
import { reactive, computed, effect } from "@vue/reactivity";
import { render, html } from "lit-html";

class TaskStats extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      tasks: [],
    });

    this.state.total = computed(() => this.state.tasks.length);
    this.state.done = computed(() => this.state.tasks.filter((t) => t.done).length);
    this.state.remaining = computed(() => this.state.tasks.filter((t) => !t.done).length);
  }

  template() {
    const s = this.state;
    return html`
      <span>${s.remaining} remaining</span>
      <span>${s.done} / ${s.total} completed</span>
    `;
  }

  connectedCallback() {
    for (const key of Object.keys(this.state)) {
      if (key in this && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) {
      this.#dispose();
      this.#dispose = null;
    }
  }
}

customElements.define("task-stats", TaskStats);
