// Generated by @jxplatform/compiler — do not edit manually
// Source: components/task-item.json
import { reactive, effect } from "@vue/reactivity";
import { render, html } from "lit-html";

class TaskItem extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      task: {},
      tasks: [],
    });

    this.state.toggleDone = ($defs) => {
      const t = $defs.task;
      const idx = $defs.tasks.findIndex((x) => x.id === t.id);
      if (idx >= 0) $defs.tasks[idx] = { ...t, done: !t.done };
    };

    this.state.removeTask = ($defs) => {
      const t = $defs.task;
      const idx = $defs.tasks.findIndex((x) => x.id === t.id);
      if (idx >= 0) $defs.tasks.splice(idx, 1);
    };
  }

  template() {
    const s = this.state;
    return html`
      <input
        type="checkbox"
        .checked="${s.task.done}"
        @click="${() => s.toggleDone(s)}"
        style="cursor: pointer; width: 18px; height: 18px;"
      />
      <span
        style="flex: 1; text-decoration: ${s.task.done ? "line-through" : "none"}; color: ${s.task
          .done
          ? "#999"
          : "#333"}"
      >
        ${s.task.text}
      </span>
      <button
        @click="${() => s.removeTask(s)}"
        style="border: none; background: none; color: #dc3545; font-size: 1.25em; cursor: pointer; padding: 0 0.25em; line-height: 1;"
      >
        ×
      </button>
    `;
  }

  connectedCallback() {
    for (const key of Object.keys(this.state)) {
      if (key in this && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) {
      this.#dispose();
      this.#dispose = null;
    }
  }
}

customElements.define("task-item", TaskItem);
