// Generated by @jxplatform/compiler — do not edit manually
// Source: task-manager.json
import "./task-item.js"; // registers <task-item>
import "./task-stats.js"; // registers <task-stats>
import { reactive, computed, effect } from "@vue/reactivity";
import { render, html } from "lit-html";

class TaskManager extends HTMLElement {
  #dispose = null;

  constructor() {
    super();
    this.state = reactive({
      tasks: [
        { id: 1, text: "Read the Jx spec", done: true },
        { id: 2, text: "Build a custom element", done: false },
        { id: 3, text: "Ship to production", done: false },
      ],
      newTaskText: "",
      nextId: 4,
      filter: "all",
    });

    this.state.addTask = ($defs) => {
      const text = $defs.newTaskText.trim();
      if (!text) return;
      $defs.tasks.push({ id: $defs.nextId++, text, done: false });
      $defs.newTaskText = "";
    };

    this.state.handleKeydown = ($defs, event) => {
      if (event.key === "Enter") $defs.addTask($defs);
    };

    this.state.filteredTasks = computed(() => {
      const f = this.state.filter;
      if (f === "active") return this.state.tasks.filter((t) => !t.done);
      if (f === "done") return this.state.tasks.filter((t) => t.done);
      return this.state.tasks;
    });

    this.state.clearDone = ($defs) => {
      $defs.tasks = $defs.tasks.filter((t) => !t.done);
    };
  }

  #filterBtn(label, value) {
    const s = this.state;
    return html`
      <button
        @click="${() => {
          s.filter = value;
        }}"
        style="flex: 1; padding: 0.6em; border: none; ${value !== "all"
          ? "border-left: 1px solid #eee;"
          : ""} cursor: pointer;
          font-weight: ${s.filter === value ? "bold" : "normal"};
          background-color: ${s.filter === value ? "#e7f1ff" : "white"};
          color: ${s.filter === value ? "#007bff" : "#666"};"
      >
        ${label}
      </button>
    `;
  }

  template() {
    const s = this.state;
    return html`
      <div style="padding: 1.25em 1em; background-color: #007bff; color: white;">
        <h2 style="margin: 0 0 0.75em; font-size: 1.3em; font-weight: 600;">Task Manager</h2>
        <div style="display: flex; gap: 0.5em;">
          <input
            type="text"
            placeholder="Add a task..."
            .value="${s.newTaskText}"
            @input="${(e) => {
              s.newTaskText = e.target.value;
            }}"
            @keydown="${(e) => s.handleKeydown(s, e)}"
            style="flex: 1; padding: 0.5em 0.75em; border: none; border-radius: 4px; font-size: 0.95em;"
          />
          <button
            @click="${() => s.addTask(s)}"
            style="padding: 0.5em 1.25em; border: none; border-radius: 4px; background-color: white; color: #007bff; font-weight: 600; cursor: pointer;"
          >
            Add
          </button>
        </div>
      </div>

      <nav style="display: flex; border-bottom: 1px solid #eee;">
        ${this.#filterBtn("All", "all")} ${this.#filterBtn("Active", "active")}
        ${this.#filterBtn("Done", "done")}
      </nav>

      <div style="background-color: white;">
        ${s.filteredTasks.map(
          (item, _index) => html`
            <task-item
              .task="${item}"
              .tasks="${s.tasks}"
              style="display: flex; align-items: center; gap: 0.75em; padding: 0.75em 1em; border-bottom: 1px solid #eee;"
            ></task-item>
          `,
        )}
      </div>

      <div
        style="display: flex; justify-content: flex-end; padding: 0.5em 1em; background-color: white; border-bottom: 1px solid #eee;"
      >
        <button
          @click="${() => s.clearDone(s)}"
          style="border: 1px solid #dee2e6; border-radius: 4px; background-color: white; color: #666; padding: 0.35em 0.75em; font-size: 0.8em; cursor: pointer;"
        >
          Clear completed
        </button>
      </div>

      <task-stats
        .tasks="${s.tasks}"
        style="display: flex; justify-content: space-between; padding: 0.75em 1em; background-color: #f8f9fa; border-radius: 0 0 8px 8px; font-size: 0.85em; color: #666;"
      ></task-stats>
    `;
  }

  connectedCallback() {
    for (const key of Object.keys(this.state)) {
      if (key in this && this[key] !== undefined) {
        this.state[key] = this[key];
      }
    }
    this.#dispose = effect(() => render(this.template(), this));
  }

  disconnectedCallback() {
    if (this.#dispose) {
      this.#dispose();
      this.#dispose = null;
    }
  }
}

customElements.define("task-manager", TaskManager);
