[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/tests/**",
  "./result/**",
  "../compiler/**",
  "../create/**",
  "../desktop/**",
  "../markup/**",
  "../parser/**",
  "../runtime/**",
  "../schema/**",
  "../server/**",
  "../site/**",
  "../starters/**",
  "../studio/**",
]
coverageThreshold = { lines = 0.99, functions = 1.0 }
