[test]
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/tests/**",
  "**/scripts/**",
  "./result/**",
  "../runtime/**",
  "../schema/**",
]
coverageThreshold = { lines = 0.96, functions = 1.0 }
