// Generates docs/extending/reference/implementation-status.md from the parsed spec status markers,
// So "what is built vs pending" lives in one place derived from the specs themselves. Regenerated by
// `bun run docs:generate`; a build output, never committed.

import { resolve } from "node:path";
import { openItems, parseSpecStatuses } from "../lib/spec-status.ts";
import { BANNER, frontmatter } from "./shared.ts";

const SPECS_DIR = resolve(import.meta.dir, "../../../specs");

/** Order non-Implemented statuses by "how far from done" for the summary grouping. */
const GROUP_ORDER = ["Partial", "Pending", "Future", "Removed"] as const;

export function generateImplementationStatus(): string {
  const specs = parseSpecStatuses(SPECS_DIR);

  const lines: string[] = [
    frontmatter(
      {
        title: "Implementation status",
        description:
          "Generated from the specs' status markers: which spec sections are implemented, partial, pending, future, or removed.",
      },
      // A projection of the specs, read from its page and not searched for by name (#305).
      { search: false },
    ),
    "",
    BANNER,
    "",
    "# Implementation status",
    "",
    "This page is generated from the `> **Status: …**` markers in the specifications. It lists every spec and the sections that are not yet fully `Implemented`. Regenerate with `bun run docs:generate`.",
    "",
    "## Specs at a glance",
    "",
    "| Spec | Version | Status | Updated |",
    "| --- | --- | --- | --- |",
  ];

  for (const spec of specs) {
    lines.push(
      `| \`${spec.file}\` | ${spec.headerVersion ?? "—"} | ${spec.headerStatus ?? "—"} | ${spec.headerUpdated ?? "—"} |`,
    );
  }

  lines.push("", "## Sections not yet implemented", "");

  /*
   * Partial and Pending come from `openItems`, not from each section's first marker, so a section
   * that leads with Implemented but admits an unbuilt part further down (a second marker, a status
   * cell in a feature table) is listed too, with where the admission is. Future and Removed are
   * read from every marker for the same reason.
   */
  const open = specs.flatMap((spec) =>
    openItems(spec).map((item) => ({
      file: spec.file,
      where: item.anchor ? `§${item.anchor}` : "whole spec",
      title: item.anchor ? item.title : "the preamble marker",
      status: item.status as string,
      note: item.leading
        ? ""
        : ` _(${item.form === "cell" ? "a status cell" : "a later marker"}, line ${item.line})_`,
    })),
  );
  const settled = specs.flatMap((spec) =>
    spec.sections.flatMap((s) =>
      (["Future", "Removed"] as const)
        .filter((status) => s.markers.some((m) => m.status === status))
        .map((status) => ({
          file: spec.file,
          where: `§${s.anchor}`,
          title: s.title,
          status: status as string,
          note: s.status === status ? "" : " _(in part)_",
        })),
    ),
  );
  const notDone = [...open, ...settled];

  if (notDone.length === 0) {
    lines.push("_Every marked section is Implemented._");
  } else {
    for (const group of GROUP_ORDER) {
      const rows = notDone.filter((s) => s.status === group);
      if (rows.length === 0) {
        continue;
      }
      lines.push(`### ${group}`, "");
      for (const r of rows) {
        lines.push(`- \`${r.file}\` ${r.where} — ${r.title}${r.note}`);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
