// Generates docs/extending/reference/implementation-status.md from the parsed spec status markers,
// So "what is built vs pending" lives in one place derived from the specs themselves. Regenerated by
// `bun run docs:generate`; CI diffs it (`bun run docs:verify`).

import { resolve } from "node:path";
import { parseSpecStatuses } from "../lib/spec-status.ts";
import { BANNER, frontmatter } from "./shared.ts";

const SPECS_DIR = resolve(import.meta.dir, "../../../specs");

/** Order non-Implemented statuses by "how far from done" for the summary grouping. */
const GROUP_ORDER = ["Partial", "Pending", "Future", "Removed"] as const;

export function generateImplementationStatus(): string {
  const specs = parseSpecStatuses(SPECS_DIR);

  const lines: string[] = [
    frontmatter(
      {
        title: "Implementation status",
        description:
          "Generated from the specs' status markers: which spec sections are implemented, partial, pending, future, or removed.",
      },
      // A projection of the specs, read from its page and not searched for by name (#305).
      { search: false },
    ),
    "",
    BANNER,
    "",
    "# Implementation status",
    "",
    "This page is generated from the `> **Status: …**` markers in the specifications. It lists every spec and the sections that are not yet fully `Implemented`. Regenerate with `bun run docs:generate`.",
    "",
    "## Specs at a glance",
    "",
    "| Spec | Version | Status | Updated |",
    "| --- | --- | --- | --- |",
  ];

  for (const spec of specs) {
    lines.push(
      `| \`${spec.file}\` | ${spec.headerVersion ?? "—"} | ${spec.headerStatus ?? "—"} | ${spec.headerUpdated ?? "—"} |`,
    );
  }

  lines.push("", "## Sections not yet implemented", "");

  const notDone = specs.flatMap((spec) =>
    spec.sections
      .filter((s) => s.status && s.status !== "Implemented")
      .map((s) => ({ file: spec.file, anchor: s.anchor, title: s.title, status: s.status })),
  );

  if (notDone.length === 0) {
    lines.push("_Every marked section is Implemented._");
  } else {
    for (const group of GROUP_ORDER) {
      const rows = notDone.filter((s) => s.status === group);
      if (rows.length === 0) {
        continue;
      }
      lines.push(`### ${group}`, "");
      for (const r of rows) {
        lines.push(`- \`${r.file}\` §${r.anchor} — ${r.title}`);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
