// Shared bits for the docs reference generators.

/** Marker every generated page must carry (check-doc-refs.ts enforces it). */
export const BANNER =
  "<!-- GENERATED by scripts/docs/generate-reference.ts — do not edit; run `bun run docs:generate`. -->";

/** The flag `check-doc-refs.ts` pairs with the banner: every generated page carries it. */
export const GENERATED_FIELD = "generated: true";

/**
 * The search opt-out, honoured per entry by `@jxsuite/search`'s `emit` (#305). It is NOT a property
 * of being generated. A generated page is a projection of data that lives elsewhere, and the
 * question is whether a reader searches for what it projects. A catalogue is searched by name — a
 * formula, an operator, a command, a shortcut, a starter, a route — and the catalogue page is the
 * right landing for that name, so those stay in the index. The three pages derived from the SPECS
 * are not searched that way: a changelog entry, a status marker and a standards row are read from
 * the page they sit on, they are regenerated on every spec release so they grow on their own, and
 * the changelog alone was 6.4% of jxsuite.com's index. The key removes a page from the INDEX only:
 * it stays in nav, in `llms.txt` and at its URL.
 */
export const SEARCH_OPT_OUT = "search: false";

/**
 * Render docs frontmatter with the generated flag, and the search opt-out when the page asks for
 * it. The default is indexed, so a new generator has to decide to leave the index, not remember
 * to.
 */
export function frontmatter(
  fields: { title: string; description: string },
  options: { search?: boolean } = {},
): string {
  return [
    "---",
    `title: "${fields.title}"`,
    `description: "${fields.description}"`,
    GENERATED_FIELD,
    ...(options.search === false ? [SEARCH_OPT_OUT] : []),
    "---",
  ].join("\n");
}
