// Generates docs/extending/reference/spec-changelog.md from the `## Changelog` section of every
// Spec, so the release history of the specifications is readable in one place. Grouped by spec
// (filename order) rather than merged into one timeline, so the output is deterministic.
// Regenerated by `bun run docs:generate`; CI diffs it (`bun run docs:verify`).

import { resolve } from "node:path";
import { parseSpecStatuses } from "../lib/spec-status.ts";
import { BANNER, frontmatter } from "./shared.ts";

const SPECS_DIR = resolve(import.meta.dir, "../../../specs");

export function generateSpecChangelog(): string {
  const specs = parseSpecStatuses(SPECS_DIR);

  const lines: string[] = [
    frontmatter(
      {
        title: "Spec changelog",
        description:
          "Release history for every specification, generated from each spec's changelog section: version, date, and what changed.",
      },
      // A projection of the specs, read from its page and not searched for by name (#305).
      { search: false },
    ),
    "",
    BANNER,
    "",
    "# Spec changelog",
    "",
    'This page is generated from the `## Changelog` section of each file in `/specs`. Every substantive spec edit is a release: the version advances, the `**Updated:**` date is restamped, and an entry lands here. Record one with `bun run spec:bump <spec.md> <major|minor|patch> -m "<what changed>"`.',
    "",
    "Versions are `MAJOR.MINOR.PATCH` — **major** for a breaking change to a documented contract, **minor** for additive behavior, **patch** for editorial changes. A `-draft` suffix marks a spec whose status is not yet `Implemented`.",
    "",
  ];

  for (const spec of specs) {
    lines.push(`## \`${spec.file}\``, "");
    if (spec.changelog.length === 0) {
      lines.push("_No changelog entries._", "");
      continue;
    }
    for (const entry of spec.changelog) {
      lines.push(`- **${entry.version}** (${entry.date}) — ${entry.summary}`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
