// Generates docs/extending/reference/spec-changelog.md from the `## Changelog` section of every
// Spec, so the release history of the specifications is readable in one place. Grouped by spec
// (filename order) rather than merged into one timeline, so the output is deterministic.
// Regenerated by `bun run docs:generate`; CI diffs it (`bun run docs:verify`).

import { resolve } from "node:path";
import { readFragments } from "../lib/spec-release.ts";
import { parseSpecStatuses } from "../lib/spec-status.ts";
import { BANNER, frontmatter } from "./shared.ts";

const ROOT = resolve(import.meta.dir, "../../..");

export function generateSpecChangelog(root: string = ROOT): string {
  const specs = parseSpecStatuses(resolve(root, "specs"));
  /* Fragments under specs/changes/ are releases recorded but not yet minted (the release lane mints
     them on the release branch), so they show as "unreleased" above the versions they will follow;
     a reader on main sees what the next release carries. */
  const pending = new Map<string, { level: string; summary: string }[]>();
  for (const fragment of readFragments(root)) {
    const list = pending.get(fragment.spec) ?? [];
    list.push({ level: fragment.level, summary: fragment.summary });
    pending.set(fragment.spec, list);
  }

  const lines: string[] = [
    frontmatter(
      {
        title: "Spec changelog",
        description:
          "Release history for every specification, generated from each spec's changelog section: version, date, and what changed.",
      },
      // A projection of the specs, read from its page and not searched for by name (#305).
      { search: false },
    ),
    "",
    BANNER,
    "",
    "# Spec changelog",
    "",
    'This page is generated from the `## Changelog` section of each file in `/specs`. Every substantive spec edit is a release: the version advances, the `**Updated:**` date is restamped, and an entry lands here. Record one with `bun run spec:change <spec.md> <major|minor|patch> -m "<what changed>"`, which the release branch mints in merge order; an entry marked **unreleased** below is one such release still waiting for the next release.',
    "",
    "Versions are `MAJOR.MINOR.PATCH` — **major** for a breaking change to a documented contract, **minor** for additive behavior, **patch** for editorial changes. A `-draft` suffix marks a spec whose status is not yet `Implemented`.",
    "",
  ];

  for (const spec of specs) {
    lines.push(`## \`${spec.file}\``, "");
    for (const entry of pending.get(spec.file) ?? []) {
      const sentence = entry.summary.endsWith(".") ? entry.summary : `${entry.summary}.`;
      lines.push(`- **unreleased** (${entry.level}) — ${sentence}`);
    }
    if (spec.changelog.length === 0 && !pending.has(spec.file)) {
      lines.push("_No changelog entries._", "");
      continue;
    }
    for (const entry of spec.changelog) {
      lines.push(`- **${entry.version}** (${entry.date}) — ${entry.summary}`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
