// Generates docs/extending/reference/standards.md from the specs' `## N. Standards Alignment`
// Tables plus the catalog, so "which external standards Jx binds itself to, and which it still
// Owes" lives in one place derived from the specs themselves. Regenerated by `bun run docs:generate`;
// CI diffs it (`bun run docs:verify`). The gate that keeps the rows honest is `bun run docs:standards`.

import { resolve } from "node:path";
import type { CatalogEntry, GapTier, StandardsRegistry } from "../lib/standards.ts";
import {
  buildRegistry,
  CITED,
  compareIds,
  CONFORMANCE_VOCAB,
  statusOfAnchor,
  tierOf,
  TIER_ORDER,
} from "../lib/standards.ts";
import { UNCITED, EXEMPT_UNNUMBERED } from "../check-standards.ts";
import { BANNER, frontmatter } from "./shared.ts";

const ROOT = resolve(import.meta.dir, "../../..");
const SPECS_DIR = resolve(ROOT, "specs");
const CATALOG_PATH = resolve(ROOT, "scripts/docs/standards.json");

interface FlatRow {
  file: string;
  id: string;
  url: string;
  cls: string;
  binds: string[];
  evidence: string[];
  note: string;
  gapId?: string;
  gapText?: string;
  rejection?: string;
  tier: GapTier | null;
}

function flatten(reg: StandardsRegistry): FlatRow[] {
  const uncited = new Set(UNCITED.map((u) => u.file));
  const out: FlatRow[] = [];
  for (const spec of reg.specs) {
    if (uncited.has(spec.file) || !spec.section) {
      continue;
    }
    const status = reg.statuses.get(spec.file);
    for (const row of spec.rows) {
      const anchors = row.binds.map((b) => b.replace(/^§/, ""));
      // A row binding several sections takes the NEAREST tier.
      let tier: GapTier | null = null;
      for (const a of anchors) {
        const t = tierOf(statusOfAnchor(status, a));
        if (t !== null && (tier === null || TIER_ORDER.indexOf(t) < TIER_ORDER.indexOf(tier))) {
          tier = t;
        }
      }
      const flat: FlatRow = {
        file: spec.file,
        id: row.id,
        url: row.url,
        cls: row.conformance ?? "",
        binds: anchors,
        evidence: row.evidence,
        note: row.note,
        tier,
      };
      if (row.gapId !== undefined) {
        flat.gapId = row.gapId;
      }
      if (row.gapText !== undefined) {
        flat.gapText = row.gapText;
      }
      if (row.rejection !== undefined) {
        flat.rejection = row.rejection;
      }
      out.push(flat);
    }
  }
  return out;
}

/** Total order: issuing body, then identifier, then spec, then first bound anchor. */
function sortKey(reg: StandardsRegistry, r: FlatRow): string {
  const org = reg.catalog.get(r.id)?.org ?? "Other";
  return `${org} ${r.id} ${r.file} ${r.binds[0] ?? ""}`;
}

function link(entry: CatalogEntry | undefined, r: FlatRow): string {
  const title = entry?.title ?? r.id;
  const url = entry?.url ?? r.url;
  return `[${title}](${url}) \`${r.id}\``;
}

/** "**Title** (RFC NNNN, `Class`)", collapsing the id when it is already the title. */
function gapHead(entry: CatalogEntry | undefined, r: FlatRow): string {
  const title = entry?.title ?? r.id;
  const qualifier = title === r.id ? `\`${r.cls}\`` : `${r.id}, \`${r.cls}\``;
  return `**${title}** (${qualifier})`;
}

function where(r: FlatRow): string {
  return r.binds.map((b) => `\`${r.file}\` §${b}`).join(", ");
}

export function generateStandards(): string {
  const reg = buildRegistry(SPECS_DIR, CATALOG_PATH);
  const rows = flatten(reg).toSorted((a, b) => compareIds(sortKey(reg, a), sortKey(reg, b)));

  const lines: string[] = [
    frontmatter(
      {
        title: "Standards alignment",
        description:
          "Generated from the specs: every external standard Jx adopts, borrows, diverges from, " +
          "or has declined — plus the tracked gaps.",
      },
      // A projection of the specs, read from its page and not searched for by name (#305).
      { search: false },
    ),
    "",
    BANNER,
    "",
    "# Standards alignment",
    "",
    "This page is generated from the `## N. Standards Alignment` tables in the specifications and " +
      "from `scripts/docs/standards.json`. The conformance vocabulary and the rules for citing a " +
      "standard live in [`specs/standards.md`](https://github.com/jxsuite/jx/blob/main/specs/standards.md). " +
      "Regenerate with `bun run docs:generate`; the rows are checked by `bun run docs:standards`.",
    "",
    "## Conformance at a glance",
    "",
    "| Class | Standards | Bindings |",
    "| --- | --- | --- |",
  ];

  const rowsOut: string[] = [];
  for (const cls of CONFORMANCE_VOCAB) {
    const matching = rows.filter((r) => r.cls === cls);
    const ids = new Set(matching.map((r) => r.id));
    const bindings = matching.reduce((n, r) => n + r.binds.length, 0);
    rowsOut.push(`| \`${cls}\` | ${ids.size} | ${bindings} |`);
  }
  rowsOut.push(`| _(backlog)_ | ${new Set(reg.backlog.map((b) => b.id)).size} | — |`);
  lines.push(...rowsOut, "", "## Standards Jx implements", "");
  const cited = rows.filter((r) => CITED.has(r.cls as never));
  if (cited.length === 0) {
    lines.push("_No standards are cited yet._");
  } else {
    lines.push("| Standard | Body | Class | Where | Evidence |", "| --- | --- | --- | --- | --- |");
    for (const r of cited) {
      const entry = reg.catalog.get(r.id);
      const evidence = r.evidence.map((e) => `\`${e}\``).join(", ");
      lines.push(
        `| ${link(entry, r)} | ${entry?.org ?? "—"} | \`${r.cls}\` | ${where(r)} | ${evidence} |`,
      );
    }
  }

  lines.push("", "## Tracked gaps", "");
  // Pending rows are gaps by definition; a Subset may name one for the half it omits.
  const gaps = rows.filter((r) => r.gapId !== undefined);
  if (gaps.length === 0) {
    lines.push("_No tracked gaps._");
  } else {
    for (const tier of TIER_ORDER) {
      const inTier = gaps.filter((r) => r.tier === tier);
      if (inTier.length === 0) {
        continue;
      }
      lines.push(`### ${tier}`, "");
      for (const r of inTier) {
        const entry = reg.catalog.get(r.id);
        const anchor = r.gapId === undefined ? "" : `<a id="gap-${r.gapId}"></a>`;
        const slug = r.gapId === undefined ? "" : `\`gap:${r.gapId}\` — `;
        lines.push(
          `- ${anchor}${slug}${gapHead(entry, r)} in ${where(r)} — ${r.gapText ?? r.note}`,
        );
      }
      lines.push("");
    }
    const untiered = gaps.filter((r) => r.tier === null);
    if (untiered.length > 0) {
      lines.push(
        "### Untiered",
        "",
        "_These bind a section carrying no status marker, so no tier can be derived._",
        "",
      );
      for (const r of untiered) {
        const entry = reg.catalog.get(r.id);
        const anchor = r.gapId === undefined ? "" : `<a id="gap-${r.gapId}"></a>`;
        const slug = r.gapId === undefined ? "" : `\`gap:${r.gapId}\` — `;
        lines.push(
          `- ${anchor}${slug}${gapHead(entry, r)} in ${where(r)} — ${r.gapText ?? r.note}`,
        );
      }
      lines.push("");
    }
  }

  lines.push("## Declined", "");
  const declined = rows.filter((r) => r.cls === "Rejected");
  if (declined.length === 0) {
    lines.push("_Nothing has been declined._", "");
  } else {
    lines.push("| Standard | Where | Because |", "| --- | --- | --- |");
    for (const r of declined) {
      const entry = reg.catalog.get(r.id);
      lines.push(`| ${link(entry, r)} | ${where(r)} | ${r.rejection ?? r.note} |`);
    }
    lines.push("");
  }

  lines.push("## Adoption backlog", "");
  if (reg.backlog.length === 0) {
    lines.push("_Nothing is waiting on a section that does not exist yet._", "");
  } else {
    lines.push(
      "Standards whose owning spec section does not exist yet, so no row can bind them. Each names " +
        "the spec that will own it; when that section is written the entry becomes a tracked gap.",
      "",
      "| Standard | Target | Why not yet |",
      "| --- | --- | --- |",
    );
    for (const b of [...reg.backlog].toSorted((x, y) => compareIds(x.id, y.id))) {
      const entry = reg.catalog.get(b.id);
      const sep = b.targetNote.startsWith("§") ? " " : " — ";
      const target =
        b.targetNote === "" ? `\`${b.target}\`` : `\`${b.target}\`${sep}${b.targetNote}`;
      const name =
        entry === undefined || entry.title === b.id
          ? `[${b.id}](${entry?.url ?? ""})`
          : `[${entry.title}](${entry.url}) \`${b.id}\``;
      lines.push(`| ${name} | ${target} | ${b.why} |`);
    }
    lines.push("");
  }

  lines.push(
    "## Standards catalog",
    "",
    "Every identifier a specification may cite, with the canonical URL the citation must use.",
    "",
    "| Id | Body | Title | Canonical URL |",
    "| --- | --- | --- | --- |",
  );
  for (const id of [...reg.catalog.keys()].toSorted(compareIds)) {
    const e = reg.catalog.get(id)!;
    lines.push(`| \`${e.id}\` | ${e.org} | ${e.title} | <${e.url}> |`);
  }

  const owed = [...UNCITED, ...EXEMPT_UNNUMBERED].toSorted((a, b) => compareIds(a.file, b.file));
  if (owed.length > 0) {
    lines.push(
      "",
      "## Specs without a Standards Alignment section",
      "",
      "| Spec | Why |",
      "| --- | --- |",
    );
    for (const u of owed) {
      lines.push(`| \`${u.file}\` | ${u.why} |`);
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
