/**
 * Compile-server.js — Hono server handler compilation
 *
 * Compiles `timing: "server"` entries from a Jx document into a deployable Hono server handler
 * file.
 */

import $RefParser from "@apidevtools/json-schema-ref-parser";
import { collectServerEntries } from "./shared.js";

/**
 * Compile a Jx document to a Hono server handler file. The handler exposes each `timing: "server"`
 * entry as a POST endpoint under `/_jx/server/$export`. Returns null if no server entries are
 * found.
 *
 * @example
 *   const server = await compileServer("./dashboard.json");
 *   if (server) fs.writeFileSync("dist/server.js", server);
 *
 * @param {string | object} sourcePath - Path to .json file, URL, or raw object
 * @param {object} [opts]
 * @param {string} [opts.baseUrl] - Base path for server endpoints. Default is `'/_jx/server'`
 * @returns {Promise<string | null>} Hono server handler source string, or null
 */
export async function compileServer(sourcePath, opts = {}) {
  const { baseUrl = "/_jx/server" } = opts;
  const doc = await $RefParser.dereference(sourcePath);
  const entries = collectServerEntries(doc);
  if (entries.length === 0) return null;

  const imports = entries
    .map(({ exportName, src }) => `import { ${exportName} } from '${src}'`)
    .join("\n");

  const routes = entries
    .map(
      ({ exportName }) => `
app.post('${baseUrl}/${exportName}', async (c) => {
  const args = await c.req.json().catch(() => ({}))
  return c.json(await ${exportName}(args))
})`,
    )
    .join("\n");

  return `// Generated by @jxplatform/compiler — do not edit manually
// Deploy as a Cloudflare Worker, Node server, or Bun process.
// Requires: npm install hono

import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}

export default app
`;
}
