/**
 * jsonsx-compiler.js — Static HTML emitter + hydration island detector
 * @version 1.0.0
 * @license MIT
 *
 * Usage (Node.js build step):
 *   node jsonsx-compiler.js <source.json> [output.html]
 *   node jsonsx-compiler.js todo-app.json > dist/todo-app.html
 *
 * Output tiers (§16.2 of spec):
 *   Fully static subtree           → plain HTML, zero JS
 *   Dynamic subtree                → <script type="application/jsonsx+json"> island
 *   timing: "server" entries       → island + generated Hono server handler
 *
 * Static detection uses the five-shape $defs grammar:
 *   - Naked values / expanded signals / template strings → dynamic (signals)
 *   - $prototype entries → dynamic (external class or Function)
 *   - Pure type defs (schema keywords only, no default) → static
 *   - ${} template strings in properties → dynamic
 *   - timing: "server" + $src + $export (no $prototype) → dynamic (server RPC)
 *
 * The compiler has zero novel static-analysis logic for JS — it reads only JSON.
 * The JSON IS the bundle manifest (§16.5).
 */

import $RefParser from '@apidevtools/json-schema-ref-parser';
import { camelToKebab, toCSSText, RESERVED_KEYS } from '@jsonsx/runtime';

// ─── Entry ────────────────────────────────────────────────────────────────────

/**
 * Compile a JSONsx document to an HTML string.
 *
 * @param {string | object} sourcePath - Path to .json file, URL, or raw object
 * @param {object}          [opts]
 * @param {string}          [opts.title='JSONsx App'] - HTML document title
 * @param {string}          [opts.runtimeSrc='./dist/runtime.js'] - Path to JSONsx runtime for islands
 * @returns {Promise<string>} Full HTML document string
 *
 * @example
 * const html = await compile('./todo-app.json', { title: 'Todo App' });
 * fs.writeFileSync('dist/index.html', html);
 */
export async function compile(sourcePath, opts = {}) {
  const { title = 'JSONsx App', runtimeSrc = './dist/runtime.js' } = opts;
  const doc = await $RefParser.dereference(sourcePath);

  const styleBlock    = compileStyles(doc);
  const bodyContent   = compileNode(doc, isNodeDynamic(doc));

  // Collect unique $src imports from $prototype: "Function" entries
  const srcImports = collectSrcImports(doc);
  const srcScript = srcImports.length
    ? `<script type="module">\n${srcImports.map(s => `  import '${s}';`).join('\n')}\n</script>`
    : '';

  const runtimeScript = hasAnyIsland(doc)
    ? `<script type="module">
  import { JSONsx } from '${runtimeSrc}';
  document.querySelectorAll('[data-jsonsx-island]').forEach(el => {
    const descriptor = el.querySelector('script[type="application/jsonsx+json"]');
    if (descriptor) JSONsx(JSON.parse(descriptor.textContent), el);
  });
</script>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  ${styleBlock}
  ${srcScript}
</head>
<body>
  ${bodyContent}
  ${runtimeScript}
</body>
</html>`;
}

// ─── Server handler compilation ───────────────────────────────────────────────

/**
 * Compile a JSONsx document to a Hono server handler file.
 * The handler exposes each `timing: "server"` entry as a POST endpoint under
 * `/_jsonsx/server/$export`. Returns null if no server entries are found.
 *
 * @param {string | object} sourcePath - Path to .json file, URL, or raw object
 * @param {object}          [opts]
 * @param {string}          [opts.baseUrl='/_jsonsx/server'] - Base path for server endpoints
 * @returns {Promise<string | null>} Hono server handler source string, or null
 *
 * @example
 * const server = await compileServer('./dashboard.json');
 * if (server) fs.writeFileSync('dist/server.js', server);
 */
export async function compileServer(sourcePath, opts = {}) {
  const { baseUrl = '/_jsonsx/server' } = opts;
  const doc = await $RefParser.dereference(sourcePath);
  const entries = collectServerEntries(doc);
  if (entries.length === 0) return null;

  const imports = entries.map(({ exportName, src }) =>
    `import { ${exportName} } from '${src}'`
  ).join('\n');

  const routes = entries.map(({ exportName }) => `
app.post('${baseUrl}/${exportName}', async (c) => {
  const args = await c.req.json().catch(() => ({}))
  return c.json(await ${exportName}(args))
})`).join('\n');

  return `// Generated by @jsonsx/compiler — do not edit manually
// Deploy as a Cloudflare Worker, Node server, or Bun process.
// Requires: npm install hono

import { Hono } from 'hono'
${imports}

const app = new Hono()
${routes}

export default app
`;
}

// ─── Static detection (§16.1) ─────────────────────────────────────────────────

/**
 * Schema-only keywords used to detect pure type definitions (Shape 2b).
 * An object with ONLY these keys and no `default` is a type def, not a signal.
 */
const SCHEMA_KEYWORDS = new Set([
  'type', 'enum', 'minimum', 'maximum', 'minLength', 'maxLength',
  'pattern', 'format', 'items', 'properties', 'required',
  'description', 'title', '$comment',
]);

/**
 * Returns true if an object contains only schema keywords (no `default`, no `$prototype`).
 */
function isSchemaOnly(obj) {
  for (const k of Object.keys(obj)) {
    if (!SCHEMA_KEYWORDS.has(k)) return false;
  }
  return true;
}

/**
 * Returns true if a string contains a ${} template expression.
 */
function isTemplateString(val) {
  return typeof val === 'string' && val.includes('${');
}

/**
 * Determine whether a node (or any of its descendants) requires client-side
 * JavaScript. A node is static if and only if its $defs contain no signals,
 * no template strings, no functions, no external classes; it has no $switch,
 * no array prototype children, no $ref bindings, and no ${} in properties.
 *
 * Five-shape detection for $defs:
 *   - string/number/boolean/null/array → dynamic (Signal.State)
 *   - string with ${} → dynamic (Signal.Computed)
 *   - object with $prototype → dynamic
 *   - object with "default" → dynamic (Signal.State)
 *   - object with schema keywords only → static (pure type def)
 *   - plain object → dynamic (Signal.State)
 *
 * @param {object} def - JSONsx element definition
 * @returns {boolean}
 */
export function isDynamic(def) {
  if (!def || typeof def !== 'object') return false;

  if (def.$defs) {
    for (const d of Object.values(def.$defs)) {
      // Non-object values are always signals → dynamic
      if (typeof d !== 'object' || d === null || Array.isArray(d)) return true;
      // Object with $prototype → dynamic (Function or external class)
      if (d.$prototype) return true;
      // Object with default → dynamic (expanded signal)
      if ('default' in d) return true;
      // Object with only schema keywords → static (pure type def, skip)
      if (isSchemaOnly(d)) continue;
      // Plain object → dynamic (Signal.State)
      return true;
    }
  }

  if (def.$switch)                           return true;
  if (def.children?.$prototype === 'Array') return true;

  if (Array.isArray(def.children)) {
    if (def.children.some(isDynamic))        return true;
  }

  for (const [key, val] of Object.entries(def)) {
    if (RESERVED_KEYS.has(key)) continue;
    if (val !== null && typeof val === 'object' && typeof val.$ref === 'string') return true;
    if (isTemplateString(val)) return true;
  }

  // Check for ${} in style values
  if (def.style && typeof def.style === 'object') {
    for (const val of Object.values(def.style)) {
      if (isTemplateString(val)) return true;
    }
  }

  // Check for ${} in attribute values
  if (def.attributes && typeof def.attributes === 'object') {
    for (const val of Object.values(def.attributes)) {
      if (isTemplateString(val)) return true;
    }
  }

  return false;
}

/**
 * Shallow variant of isDynamic — checks only this node's own properties,
 * not its children. Used at compile() root so a static parent with dynamic
 * children emits plain HTML at the root while children become islands.
 *
 * @param {object} def
 * @returns {boolean}
 */
function isNodeDynamic(def) {
  if (!def || typeof def !== 'object') return false;

  if (def.$defs) {
    for (const d of Object.values(def.$defs)) {
      if (typeof d !== 'object' || d === null || Array.isArray(d)) return true;
      if (d.$prototype) return true;
      if ('default' in d) return true;
      if (isSchemaOnly(d)) continue;
      return true;
    }
  }

  if (def.$switch)                           return true;
  if (def.children?.$prototype === 'Array') return true;

  for (const [key, val] of Object.entries(def)) {
    if (RESERVED_KEYS.has(key)) continue;
    if (val !== null && typeof val === 'object' && typeof val.$ref === 'string') return true;
    if (isTemplateString(val)) return true;
  }

  if (def.style && typeof def.style === 'object') {
    for (const val of Object.values(def.style)) {
      if (isTemplateString(val)) return true;
    }
  }

  if (def.attributes && typeof def.attributes === 'object') {
    for (const val of Object.values(def.attributes)) {
      if (isTemplateString(val)) return true;
    }
  }

  return false;
}

/**
 * Returns true if any node in the tree will be emitted as a hydration island.
 *
 * @param {object} def
 * @returns {boolean}
 */
function hasAnyIsland(def) {
  if (!def || typeof def !== 'object') return false;
  if (isDynamic(def)) return true;
  if (Array.isArray(def.children)) return def.children.some(hasAnyIsland);
  return false;
}

// ─── Node compilation ─────────────────────────────────────────────────────────

/**
 * Compile a single JSONsx node to an HTML string.
 * Dynamic nodes become hydration islands; static nodes become plain HTML.
 *
 * @param {object}  def     - Element definition
 * @param {boolean} dynamic - Whether this node is dynamic
 * @returns {string} HTML string
 */
function compileNode(def, dynamic) {
  if (dynamic) {
    const tag = def.tagName ?? 'div';
    return `<${tag} data-jsonsx-island>
  <script type="application/jsonsx+json">${JSON.stringify(def, null, 2)}</script>
</${tag}>`;
  }

  const tag   = def.tagName ?? 'div';
  const attrs = buildAttrs(def);
  const inner = buildInner(def);

  return `<${tag}${attrs}>${inner}</${tag}>`;
}

/**
 * Build an HTML attribute string from a static element definition.
 *
 * @param {object} def
 * @returns {string}
 */
function buildAttrs(def) {
  let out = '';

  if (def.id)         out += ` id="${escapeHtml(def.id)}"`;
  if (def.className)  out += ` class="${escapeHtml(def.className)}"`;
  if (def.hidden)     out += ` hidden`;
  if (def.tabIndex !== undefined) out += ` tabindex="${def.tabIndex}"`;
  if (def.title)      out += ` title="${escapeHtml(def.title)}"`;
  if (def.lang)       out += ` lang="${escapeHtml(def.lang)}"`;
  if (def.dir)        out += ` dir="${escapeHtml(def.dir)}"`;

  // Inline style (static, no nested selectors)
  if (def.style) {
    const inline = Object.entries(def.style)
      .filter(([k]) => !k.startsWith(':') && !k.startsWith('.') &&
                       !k.startsWith('&') && !k.startsWith('['))
      .map(([k, v]) => `${camelToKebab(k)}: ${v}`)
      .join('; ');
    if (inline) out += ` style="${inline}"`;
  }

  // Custom attributes
  if (def.attributes) {
    for (const [k, v] of Object.entries(def.attributes)) {
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') {
        out += ` ${k}="${escapeHtml(String(v))}"`;
      }
    }
  }

  return out;
}

/**
 * Build the inner HTML (textContent or children) for a static node.
 *
 * @param {object} def
 * @returns {string}
 */
function buildInner(def) {
  if (typeof def.textContent === 'string') return escapeHtml(def.textContent);
  if (def.innerHTML) return def.innerHTML; // trusted static HTML
  if (Array.isArray(def.children)) {
    return def.children
      .map(c => compileNode(c, isDynamic(c)))
      .join('\n  ');
  }
  return '';
}

// ─── Style extraction (§16.4) ─────────────────────────────────────────────────

/**
 * Walk the entire document tree and collect all static nested CSS rules into a
 * single `<style>` block for the document `<head>`.
 * Static inline styles are emitted as HTML style attributes, not here.
 *
 * @param {object} doc - Root document
 * @returns {string} `<style>` HTML string, or empty string if no rules
 */
function compileStyles(doc) {
  const rules = [];
  collectStyles(doc, rules, '');
  if (rules.length === 0) return '';
  return `<style>\n${rules.join('\n')}\n</style>`;
}

/**
 * Recursively collect nested CSS rules from style definitions.
 *
 * @param {object}   def            - Element definition
 * @param {string[]} rules          - Accumulator for CSS rule strings
 * @param {string}   [parentSel=''] - Inherited CSS selector context
 */
function collectStyles(def, rules, _parentSel = '') {
  if (!def || typeof def !== 'object') return;

  const selector = def.id
    ? `#${def.id}`
    : def.className
      ? `.${def.className.split(' ')[0]}`
      : (def.tagName ?? '*');

  if (def.style) {
    for (const [prop, val] of Object.entries(def.style)) {
      if (prop.startsWith(':') || prop.startsWith('.') ||
          prop.startsWith('&') || prop.startsWith('[')) {
        const resolved = prop.startsWith('&')
          ? prop.replace('&', selector)
          : `${selector}${prop}`;
        rules.push(`${resolved} { ${toCSSText(val)} }`);
      }
    }
  }

  if (Array.isArray(def.children)) {
    def.children.forEach(c => collectStyles(c, rules, selector));
  }
}

// ─── Utilities ────────────────────────────────────────────────────────────────

/**
 * Recursively collect unique $src values from $prototype: "Function" entries.
 *
 * @param {object} doc - Document or subtree
 * @returns {string[]} Unique $src paths
 */
function collectSrcImports(doc) {
  const srcs = new Set();
  _walkSrc(doc, srcs);
  return [...srcs];
}

function _walkSrc(def, srcs) {
  if (!def || typeof def !== 'object') return;
  if (def.$defs) {
    for (const d of Object.values(def.$defs)) {
      if (d && typeof d === 'object' && d.$prototype === 'Function' && d.$src) {
        srcs.add(d.$src);
      }
    }
  }
  if (Array.isArray(def.children)) {
    def.children.forEach(c => _walkSrc(c, srcs));
  }
}

/**
 * Recursively collect all `timing: "server"` entries from the document tree.
 * Returns unique entries keyed by export name (last definition wins on conflict).
 *
 * @param {object} doc - Document or subtree
 * @returns {{ key: string, exportName: string, src: string }[]}
 */
function collectServerEntries(doc) {
  const entries = new Map();
  _walkServerEntries(doc, entries);
  return [...entries.values()];
}

function _walkServerEntries(def, entries) {
  if (!def || typeof def !== 'object') return;
  if (def.$defs) {
    for (const [key, d] of Object.entries(def.$defs)) {
      if (d && typeof d === 'object' && d.timing === 'server' && d.$src && d.$export && !d.$prototype) {
        entries.set(d.$export, { key, exportName: d.$export, src: d.$src });
      }
    }
  }
  if (Array.isArray(def.children)) {
    def.children.forEach(c => _walkServerEntries(c, entries));
  }
}

/**
 * HTML-escape a string for safe attribute and text content embedding.
 *
 * @param {string} str
 * @returns {string}
 */
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ─── CLI ──────────────────────────────────────────────────────────────────────

if (process.argv[2]) {
  const [,, src, out] = process.argv;

  Promise.all([compile(src), compileServer(src)])
    .then(async ([html, server]) => {
      const { writeFileSync } = await import('node:fs');
      if (out) {
        writeFileSync(out, html, 'utf8');
        console.error(`Written to ${out}`);
      } else {
        process.stdout.write(html);
      }
      if (server && out) {
        const serverOut = out.replace(/(\.[^.]+)?$/, '-server.js');
        writeFileSync(serverOut, server, 'utf8');
        console.error(`Server handler written to ${serverOut}`);
      }
    })
    .catch(err => {
      console.error(err);
      process.exit(1);
    });
}
